const rusKeys = [
  {
    "key": "ё",
    "key2": "Ё",
    "keyCode": 192,
    "code": "Backquote",
    "class": "key",
  },
  {
    "key": "1",
    "key2": "!",
    "keyCode": 49,
    "code": "Digit1",
    "class": "key",
  },
  {
    "key": "2",
    "keyCode": 50,
    "key2": '"',
    "code": "Digit2",
    "class": "key",
  },
  {
    "key": "3",
    "key2": '№',
    "code": "Digit3",
    "keyCode": 51,
    "class": "key",
  },
  {
    "key": "4",
    "key2": ';',
    "code": "Digit4",
    "keyCode": 52,
    "class": "key",
  },
  {
    "key": "5",
    "key2": '%',
    "code": "Digit5",
    "keyCode": 53,
    "class": "key",
  },
  {
    "key": "6",
    "key2": ':',
    "code": "Digit6",
    "keyCode": 54,
    "class": "key",
  },
  {
    "key": "7",
    "key2": '?',
    "code": "Digit7",
    "keyCode": 55,
    "class": "key",
  },
  {
    "key": "8",
    "key2": '*',
    "code": "Digit8",
    "keyCode": 56,
    "class": "key",
  },
  {
    "key": "9",
    "key2": '(',
    "code": "Digit9",
    "keyCode": 57,
    "class": "key",
  },
  {
    "key": "0",
    "key2": ')',
    "code": "Digit0",
    "keyCode": 48,
    "class": "key",
  },
  {
    "key": "-",
    "key2": "_",
    "code": "Minus",
    "keyCode": 189,
    "class": "key",
  },
  {
    "key": "=",
    "key2": "+",
    "code": "Equal",
    "keyCode": 187,
    "class": "key",
  },
  {
    "key": "Backspace",
    "keyCode": 8,
    "code": "Backspace",
    "class": "key Backspace",
  },
  {
    "key": "Tab",
    "keyCode": 9,
    "code": "Tab",
    "class": "key Tab",
  },
  {
    "key": "й",
    "code": "KeyQ",
    "keyCode": 81,
    "class": "key",
  },
  {
    "key": "ц",
    "code": "KeyW",
    "keyCode": 87,
    "class": "key",
  },
  {
    "key": "у",
    "code": "KeyE",
    "keyCode": 69,
    "class": "key",
  },
  {
    "key": "к",
    "code": "KeyR",
    "keyCode": 82,
    "class": "key",
  },
  {
    "key": "е",
    "code": "KeyT",
    "keyCode": 84,
    "class": "key",
  },
  {
    "key": "н",
    "code": "KeyY",
    "keyCode": 89,
    "class": "key",
  },
  {
    "key": "г",
    "code": "KeyU",
    "keyCode": 85,
    "class": "key",
  },
  {
    "key": "ш",
    "code": "KeyI",
    "keyCode": 73,
    "class": "key",
  },
  {
    "key": "щ",
    "code": "KeyO",
    "keyCode": 79,
    "class": "key",
  },
  {
    "key": "з",
    "code": "KeyP",
    "keyCode": 80,
    "class": "key",
  },
  {
    "key": "х",
    "code": "BracketLeft",
    "keyCode": 219,
    "class": "key",
  },
  {
    "key": "ъ",
    "code": "BrackeRight",
    "keyCode": 221,
    "class": "key",
  },
  {
    "key": "\\",
    "key2": "|",
    "keyCode": 220,
    "code": "Backslash",
    "class": "key Slash",
  },
  {
    "key": "CapsLock",
    "keyCode": 20,
    "code": "CapsLock",
    "class": "key CapsLock",
  },
  {
    "key": "ф",
    "code": "KeyA",
    "keyCode": 65,
    "class": "key",
  },
  {
    "key": "ы",
    "code": "KeyS",
    "keyCode": 83,
    "class": "key",
  },
  {
    "key": "в",
    "code": "KeyD",
    "keyCode": 68,
    "class": "key",
  },
  {
    "key": "а",
    "code": "KeyF",
    "keyCode": 70,
    "class": "key",
  },
  {
    "key": "п",
    "code": "KeyG",
    "keyCode": 71,
    "class": "key",
  },
  {
    "key": "р",
    "code": "KeyH",
    "keyCode": 72,
    "class": "key",
  },
  {
    "key": "о",
    "code": "KeyJ",
    "keyCode": 74,
    "class": "key",
  },
  {
    "key": "л",
    "code": "KeyK",
    "keyCode": 75,
    "class": "key",
  },
  {
    "key": "д",
    "code": "KeyL",
    "keyCode": 76,
    "class": "key",
  },
  {
    "key": "ж",
    "code": "Semicolon",
    "keyCode": 186,
    "class": "key",
  },
  {
    "key": "э",
    "code": "Quote",
    "keyCode": 222,
    "class": "key",
  },
  {
    "key": "Enter",
    "keyCode": 13,
    "code": "Enter",
    "class": "key Enter",
  },
  {
    "key": "Shift",
    "keyCode": 16,
    "code": "ShiftLeft",
    "class": "key ShiftLeft",
  },
  {
    "key": "я",
    "code": "KeyZ",
    "keyCode": 90,
    "class": "key",
  },
  {
    "key": "ч",
    "code": "KeyX",
    "keyCode": 88,
    "class": "key",
  },
  {
    "key": "с",
    "code": "KeyC",
    "keyCode": 67,
    "class": "key",
  },
  {
    "key": "м",
    "code": "KeyV",
    "keyCode": 86,
    "class": "key",
  },
  {
    "key": "и",
    "code": "KeyB",
    "keyCode": 66,
    "class": "key",
  },
  {
    "key": "т",
    "code": "KeyN",
    "keyCode": 78,
    "class": "key",
  },
  {
    "key": "ь",
    "code": "KeyM",
    "keyCode": 77,
    "class": "key",
  },
  {
    "key": "б",
    "keyCode": 188,
    "code": "Comma",
    "class": "key",
  },
  {
    "key": "ю",
    "keyCode": 190,
    "code": "Period",
    "class": "key",
  },
  {
    "key": ".",
    "keyCode": 191,
    "code": "Slash",
    "class": "key",
  },
  {
    "key": "&uarr;",
    "keyCode": 38,
    "code": "ArrowUp",
    "class": "key ArrowUp",
  },
  {
    "key": "Shift",
    "keyCode": 16,
    "code": "ShiftRight",
    "class": "key ShiftRight",
  },
  {
    "key": "Ctrl",
    "keyCode": 17,
    "code": "ControlLeft",
    "class": "key ControlLeft",
  },
  {
    "key": "Del",
    "keyCode": 46,
    "code": "Delete",
    "class": "key  Delete",
  },
  {
    "key": "Win",
    "keyCode": 91,
    "code": "MetaLeft",
    "class": "key MetaLeft",
  },
  {
    "key": "Alt",
    "keyCode": 18,
    "code": "AltLeft",
    "class": "key AltLeft",
  },
  {
    "key": " ",
    "keyCode": 32,
    "code": "Space",
    "class": "key Space",
  },
  {
    "key": "Alt",
    "keyCode": 18,
    "code": "AltRight",
    "class": "key AltRight",
  },
  {
    "key": "&larr;",
    "keyCode": 37,
    "code": "ArrowLeft",
    "class": "key ArrowLeft",
  },
    {
    "key": "&darr;",
    "keyCode": 40,
    "code": "ArrowDown",
    "class": "key ArrowDown",
  },
  {
    "key": "&rarr;",
    "keyCode": 39,
    "code": "ArrowRight",
    "class": "key ArrowRight",
  },
  {
    "key": "Ctrl",
    "keyCode": 17,
    "code": "ControlRight",
    "class": "key ControlRight",
  },
];

export { rusKeys };
