const winKeys = [
  {
    "key": "`",
    "key2": "~",
    "keyCode": 192,
    "code": "Backquote",
    "class": "key",
  },
  {
    "key": "1",
    "key2": "!",
    "keyCode": 49,
    "code": "Digit1",
    "class": "key",
  },
  {
    "key": "2",
    "key2": "@",
    "keyCode": 50,
    "code": "Digit2",
    "class": "key",
  },
  {
    "key": "3",
    "key2": "#",
    "keyCode": 51,
    "code": "Digit3",
    "class": "key",
  },
  {
    "key": "4",
    "key2": "$",
    "keyCode": 52,
    "code": "Digit4",
    "class": "key",
  },
  {
    "key": "5",
    "key2": "%",
    "keyCode": 53,
    "code": "Digit5",
    "class": "key",
  },
  {
    "key": "6",
    "key2": "^",
    "keyCode": 54,
    "code": "Digit6",
    "class": "key",
  },
  {
    "key": "7",
    "key2": "&",
    "keyCode": 55,
    "code": "Digit7",
    "class": "key",
  },
  {
    "key": "8",
    "key2": "*",
    "keyCode": 56,
    "code": "Digit8",
    "class": "key",
  },
  {
    "key": "9",
    "key2": "(",
    "keyCode": 57,
    "code": "Digit9",
    "class": "key",
  },
  {
    "key": "0",
    "key2": ")",
    "keyCode": 48,
    "code": "Digit0",
    "class": "key",
  },
  {
    "key": "-",
    "key2": "_",
    "keyCode": 189,
    "code": "Minus",
    "class": "key",
  },
  {
    "key": "=",
    "key2": "+",
    "keyCode": 187,
    "code": "Equal",
    "class": "key",
  },
  {
    "key": "Backspace",
    "keyCode": 8,
    "code": "Backspace",
    "class": "key Backspace",
  },
  {
    "key": "Tab",
    "keyCode": 9,
    "code": "Tab",
    "class": "key Tab",
  },
  {
    "key": "q",
    "keyCode": 81,
    "code": "KeyQ",
    "class": "key",
  },
  {
    "key": "w",
    "keyCode": 87,
    "code": "KeyW",
    "class": "key",
  },
  {
    "key": "e",
    "keyCode": 69,
    "code": "KeyE",
    "class": "key",
  },
  {
    "key": "r",
    "keyCode": 82,
    "code": "KeyR",
    "class": "key",
  },
  {
    "key": "t",
    "keyCode": 84,
    "code": "KeyT",
    "class": "key",
  },
  {
    "key": "y",
    "keyCode": 89,
    "code": "KeyY",
    "class": "key",
  },
  {
    "key": "u",
    "keyCode": 85,
    "code": "KeyU",
    "class": "key",
  },
  {
    "key": "i",
    "keyCode": 73,
    "code": "KeyI",
    "class": "key",
  },
  {
    "key": "o",
    "keyCode": 79,
    "code": "KeyO",
    "class": "key",
  },
  {
    "key": "p",
    "keyCode": 80,
    "code": "KeyP",
    "class": "key",
  },
  {
    "key": "[",
    "key2": "{",
    "keyCode": 219,
    "code": "BracketLeft",
    "class": "key",
  },
  {
    "key": "]",
    "key2": "}",
    "keyCode": 221,
    "code": "BracketRight",
    "class": "key",
  },
  {
    "key": "\\",
    "key2": "|",
    "keyCode": 220,
    "code": "Backslash",
    "class": "key Slash",
  },
  {
    "key": "CapsLock",
    "keyCode": 20,
    "code": "CapsLock",
    "class": "key CapsLock",
  },
  {
    "key": "a",
    "keyCode": 65,
    "code": "KeyA",
    "class": "key",
  },
  {
    "key": "s",
    "keyCode": 83,
    "code": "KeyS",
    "class": "key",
  },
  {
    "key": "d",
    "keyCode": 68,
    "code": "KeyD",
    "class": "key",
  },
  {
    "key": "f",
    "keyCode": 70,
    "code": "KeyF",
    "class": "key",
  },
  {
    "key": "g",
    "keyCode": 71,
    "code": "KeyG",
    "class": "key",
  },
  {
    "key": "h",
    "keyCode": 72,
    "code": "KeyH",
    "class": "key",
  },
  {
    "key": "j",
    "keyCode": 74,
    "code": "KeyJ",
    "class": "key",
  },
  {
    "key": "k",
    "keyCode": 75,
    "code": "KeyK",
    "class": "key",
  },
  {
    "key": "l",
    "keyCode": 76,
    "code": "KeyL",
    "class": "key",
  },
  {
    "key": ";",
    "key2": ":",
    "keyCode": 186,
    "code": "Semicolon",
    "class": "key",
  },
  {
    "key": "'",
    "key2": '"',
    "keyCode": 222,
    "code": "Quote",
    "class": "key",
  },
  {
    "key": "Enter",
    "keyCode": 13,
    "code": "Enter",
    "class": "key Enter",
  },
  {
    "key": "Shift",
    "keyCode": 16,
    "code": "ShiftLeft",
    "class": "key ShiftLeft",
  },
  {
    "key": "z",
    "keyCode": 90,
    "code": "KeyZ",
    "class": "key",
  },
  {
    "key": "x",
    "keyCode": 88,
    "code": "KeyX",
    "class": "key",
  },
  {
    "key": "c",
    "keyCode": 67,
    "code": "KeyC",
    "class": "key",
  },
  {
    "key": "v",
    "keyCode": 86,
    "code": "KeyV",
    "class": "key",
  },
  {
    "key": "b",
    "keyCode": 66,
    "code": "KeyB",
    "class": "key",
  },
  {
    "key": "n",
    "keyCode": 78,
    "code": "KeyN",
    "class": "key",
  },
  {
    "key": "m",
    "keyCode": 77,
    "code": "KeyM",
    "class": "key",
  },
  {
    "key": ",",
    "key2": "<",
    "keyCode": 188,
    "code": "Comma",
    "class": "key",
  },
  {
    "key": ".",
    "key2": ">",
    "keyCode": 190,
    "code": "Period",
    "class": "key",
  },
  {
    "key": "/",
    "key2": "?",
    "keyCode": 191,
    "code": "Slash",
    "class": "key",
  },
  {
    "key": "&uarr;",
    "keyCode": 38,
    "code": "ArrowUp",
    "class": "key ArrowUp",
  },
  {
    "key": "Shift",
    "keyCode": 16,
    "code": "ShiftRight",
    "class": "key ShiftRight",
  },
  {
    "key": "Ctrl",
    "keyCode": 17,
    "code": "ControlLeft",
    "class": "key ControlLeft",
  },
  {
    "key": "Del",
    "keyCode": 46,
    "code": "Delete",
    "class": "key  Delete",
  },
  {
    "key": "Win",
    "keyCode": 91,
    "code": "MetaLeft",
    "class": "key MetaLeft",
  },
  {
    "key": "Alt",
    "keyCode": 18,
    "code": "AltLeft",
    "class": "key AltLeft",
  },
  {
    "key": " ",
    "keyCode": 32,
    "code": "Space",
    "class": "key Space",
  },
  {
    "key": "Alt",
    "keyCode": 18,
    "code": "AltRight",
    "class": "key AltRight",
  },
  {
    "key": "&larr;",
    "keyCode": 37,
    "code": "ArrowLeft",
    "class": "key ArrowLeft",
  },
    {
    "key": "&darr;",
    "keyCode": 40,
    "code": "ArrowDown",
    "class": "key ArrowDown",
  },
  {
    "key": "&rarr;",
    "keyCode": 39,
    "code": "ArrowRight",
    "class": "key ArrowRight",
  },
  {
    "key": "Ctrl",
    "keyCode": 17,
    "code": "ControlRight",
    "class": "key ControlRight",
  },
];

export { winKeys };
